export const UPDATE_PROFILE_DATA = 'GET_PROFILE_DATA';
export const UPDATE_REPO_DATA = 'GET_REPO_DATA';
export const HANDLE_SERVER_ERROR = 'HANDLE_SERVER_ERROR';
export const HANDLE_LOADER_VISIBILITY = 'HANDLE_LOADER_VISIBILITY';

export const HANDLE_REPOSITORY_SEARCH = 'HANDLE_REPOSITORY_SEARCH';
export const HANDLE_FILTER_BY_TYPE = 'HANDLE_FILTER_BY_TYPE';
export const HANDLE_FILTER_BY_LANGUAGE = 'HANDLE_FILTER_BY_LANGUAGE';
export const HANDLE_UPDATE_FILTER_TYPE = 'HANDLE_UPDATE_FILTER_TYPE'